### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by rcgreene43** [theishiopian/ProjectPsi#2]
Every time I try and move via the teleport I fall through the floor. 
I believe this is a non combat build I am not sure as I couldn't get far enough to find enemies.
Just use the teleport, I was able to replicate it 3 times in a row.

commit e144bd70e76cda42866a9d44c84521caa1748ff2

**Comment by theishiopian** [comment]
I dont see that on my end, can you get me some positions in the level where it happens? also whats the framerate like on your end?

**Comment by theishiopian** [comment]
Can't reproduce as of latest, will keep an eye on it

**Comment by theishiopian** [comment]
Seems to be related to #19, moving there for now
