### ISSUE TITLE
Occlusion culling in final room

### ISSUE THREAD

**Issue by marcusbbb12** [theishiopian/ProjectPsi#4]
With the final room set up as is, the end of the room gets  culled out. If I made it just a tad shorter the problem would be solved. Just something for us to think about.

**Comment by theishiopian** [comment]
need to increase far plane range

**Comment by theishiopian** [comment]
I increased the camera far plane, should make it render the whole thing

**Comment by theishiopian** [comment]
Fixed in d53d46d3c9cf9883cfc95bb17029d950b55271af
