### ISSUE TITLE
Difficulty teleporting

### ISSUE THREAD

**Issue by marcusbbb12** [theishiopian/ProjectPsi#9]
I am personally having some trouble teleporting. The teleport and angle turn are both mapped to the right stick. Trying to teleport often times results in the player simply turning and not teleporting. I think we need a little bit more wiggle room when pushing the stick forward so that the game reads the input as a teleport and not a turn.

**Comment by theishiopian** [comment]
i have this problem as well, the issue is you can still turn while readying a teleport. i will fix this tomorrow
